### ISSUE TITLE
I changed the parameter "real_images" to False and got the error.

### ISSUE THREAD

**Issue by iamzhouh** [valeoai/OCTET#2]
I changed the parameter `real_images `to False and got the error `"UnboundLocalError: local variable 'iterator' referenced before assignment"`. The error is reported in "https://github.com/valeoai/OCTET/blob/58e756580162cc54a7c89f33c1aa76f3bfc0215e/octet_invert_counterfactual.py#LL158C9-L158C86", that is, if `real_images` is changed to False, `target` is called without definition. How to solve it?

**Comment by EloiZ** [comment]
Hello, thanks for your interest in our work. Can you please send me the whole command line?
Best,

**Comment by iamzhouh** [comment]
Thank you for replying to my question. When I set `real_images` to `False`, I get an error:
```
Backtracking (last call):
  File "OCTET/octet_invert_counterfactual.py", line 301, in <module>.
    octet.invert_and_cf()
  File "OCTET/octet_invert_counterfactual.py", line 158, in invert_and_cf
    metadata, images = self.cf_optim(metadata, images, target.to(opt.device))
UnboundLocalError: local variable 'target' is referenced before assignment
```
Also, in the case that I did not change any parameters (except `dataset_path`) and the default `real_images` is `True` without change, the project works, but the generated counterfactual images are messy and meaningless images.

**Comment by EloiZ** [comment]
Good to know that with `real_images=True` it works.
I just pushed updated code, please update your local repository
It should work with `real_images=False`, let me know if it is not the case.
Also, do not hesitate to try various hyperparameters to explore various counterfactual strengths. The most important parameter is the `lambda_prox` param that balances between "staying close the original image" and "change the classifier decision".
